### PR TITLE
Support nested duals

### PR DESCRIPTION
**Pull request by thomvet**
Pull request makes slight changes to dualcache() including some dispatching. 

The net result of the change is that nesting Dual numbers is now possible and occurs in a controllable manner. This enables, for example, second derivatives to be calculated or when automatic differentiation occurs both in an optimizer (gradients, hessians [inefficient, but it works!]) and inside an ODE solver (that gets called inside the objective function to be optimized).

Examples in the form of tests are provided in `core_nesteddual.jl`.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Oh could you also update the README? It's using the old chunk size specification still I think

**Comment by ChrisRackauckas** [comment]
Tests passed here but failed after merging. https://github.com/SciML/PreallocationTools.jl/runs/4096310917?check_suite_focus=true#step:6:286 odd

**Comment by thomvet** [comment]
Ok, it wasn’t the smartest idea to include a test involving random numbers as coefficients for an ODE system and then checking accuracy of the solution of the optimizer… I repeated tests locally and it only failed on the 8th run. So, with an unlucky draw of numbers it fails. I’ll change to fixed coefficients and fixed initial point.

**Comment by ChrisRackauckas** [comment]
Oh, makes sense. I didn't check for that. Thanks. Other than that, it all looks good.

**Pull request merged**
