### PR TITLE
Add buildkite badges

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Looks like we're cooking?

**Comment by ChrisRackauckas** [comment]
Chicken noodle soup.

**Comment by ChrisRackauckas** [comment]
`echo 'hello world'`, looks like it's not running the buildkite script but something prewritten?

**Comment by DilumAluthge** [comment]
You'll need to update the steps here: https://buildkite.com/julialang/preallocationtools-dot-jl/steps

Probably you just want to copy the example steps from the instructions here: https://github.com/JuliaGPU/buildkite#adding-a-repository

**Comment by DilumAluthge** [comment]
E.g. something like 

```yaml
steps:
  - label: ":buildkite: Pipeline upload"
    command: buildkite-agent pipeline upload
    branches: "!gh-pages"
    agents:
      queue: "juliagpu"
```

**Comment by DilumAluthge** [comment]
Once you've edited the steps, you can try closing and reopening this PR, or force-pushing a new commit to this PR.

**Pull request closed without merging**
