### PR TITLE
Bump ArrayInterface v4

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
@chriselrod is this known?

**Comment by chriselrod** [comment]
> @chriselrod is this known?

Yes. Do you need ArrayInterface 0.4?
https://github.com/JuliaSIMD/VectorizationBase.jl/blob/1b6cdc4d721bce66f724ef08d831994720ab420b/Project.toml#L19-L26
https://github.com/JuliaSIMD/LoopVectorization.jl/blob/5f71046e216582ed8a34325de13b272c444a138e/Project.toml#L28-L42

**Comment by ChrisRackauckas** [comment]
Don't need, was just tracking it.

**Comment by Tokazama** [comment]
I can start looking into it.

**Pull request closed without merging**
